### PR TITLE
Update to work with non-200 jenkins responses

### LINKED ISSUE #10: jenkins returns response 201 when kicking a job
New versions of Jenkins will fire a 201 reponse vs a 200. A quick cowboy 

```
diff --git a/src/jenkinsgithublander/jenkins.py b/src/jenkinsgithublander/jenkins.py
index f92eaa6..0e87e80 100644
--- a/src/jenkinsgithublander/jenkins.py
+++ b/src/jenkinsgithublander/jenkins.py
@@ -38,5 +38,5 @@ def kick_jenkins_merge(pr_id, git_sha, jenkins_info):
     }

     resp = requests.post(url, request_data)
-    if resp.status_code != 200:
+    if resp.status_code != 200 and resp.status_code != 201:
         raise JenkinsError(resp.content)
```

### PR DESCRIPTION
**Pull request by mitechie**
- Jenkins started sending back 201 "created" for kicked jobs
- Add a test that it raises the appropriate exception for a 404 response as an
  error case.
- Fixes #10

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/23/

**Comment by mitechie** [comment]
Re ran tests and passed http://ci.jujugui.org:8080/job/jenkins-github-lander/24

**Comment by jcsackett** [comment]
LGTM, thanks.

**Comment by kadams54** [comment]
LGTM as well.

**Comment by mitechie** [comment]
:shipit: thanks for the quick reviews.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jenkins-github-lander-merge

**Pull request merged**
