### PR TITLE
Make sure to send json bodies to github api.

### PR DESCRIPTION
**Pull request by mitechie**
- A 20X is a valid return code. Github uses 201 for a new comment.
- Submit a merge with the message being the 'body' of the pull request.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/10/

**Comment by mitechie** [comment]
Haha, test failed. It's a branch in progress so will be updating for follow up. Just wanted to see it auto-die.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/11/

**Comment by mitechie** [comment]
Cool, I was curious if I could rebase and then force push to clean up the proposal before landing.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/12/

**Comment by mitechie** [comment]
$$merge$$

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jenkins-github-lander-merge/buildWithParameters

**Pull request merged**
