### PR TITLE
Handle errors on merging via github api better

### PR DESCRIPTION
**Pull request by bz2**
Several improvements to the error handling of the lander-merge-result job.
Returns non-zero error code on failure and prints errors to stderr. Also
copes with a weird api issue where the pr is reported as not mergable but
lacks the 'merged' key in the response.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/28/

**Comment by axw** [comment]
LGTM

**Comment by mitechie** [comment]
Thanks for these updates. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jenkins-github-lander-merge

**Pull request merged**
