### PR TITLE
Add PullRequestInfo with extra details

### PR DESCRIPTION
**Pull request by bz2**
Pass more details about the pull request through to jenkins. Refactor with
new PullRequestInfo type constructed from the json api response to simplify
the passing around of details about pull requests.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/32/

**Comment by axw** [comment]
LGTM

**Comment by mitechie** [comment]
:shipit:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/35/

**Comment by bz2** [comment]
Rebased to update the new test landed on develop.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jenkins-github-lander-merge

**Pull request merged**
