### PR TITLE
Fix lint.  

### PR DESCRIPTION
**Pull request by bac**
- Change the Makefile to lint as part of 'make test'.
- Fix lint.
- Add 'all' as a dependency on 'test'.

### CODE REVIEW

**Comment by bac** [comment]
This branch does not pass lint as a test of the Jenkins merge failure reporting.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/49/

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jenkins-github-lander-merge

**Comment by bac** [comment]
Closing this PR to try again.

**Pull request closed without merging**
