### PR TITLE
Support checking and triggering builds on multiple projects.

### PR DESCRIPTION
**Pull request by mitechie**
- Update the INI docs with examples of listing multiple projects
- Add checks for parsing those and verifying they're sane.
- Add new job-name to the landing job so that we can identify which projects
  we're landing.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/18/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/19/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/jenkins-github-lander/20/

**Comment by mitechie** [comment]
$$merge$$

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/jenkins-github-lander-merge

**Pull request merged**
